export const REQUEST_PAGES = 'REQUEST_PAGES'
export const RECEIVE_PAGES = 'RECEIVE_PAGES'

export const SET_PUBLISH_STATUS_FILTER = 'SET_PUBLISH_STATUS_FILTER'
export const SET_TEXT_SEARCH_FILTER = 'SET_TEXT_SEARCH_FILTER'

export const CREATE_PAGE_REQUEST = 'CREATE_PAGE_REQUEST'
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS'
export const CREATE_PAGE_FAILURE = 'CREATE_PAGE_FAILURE'

export const TOGGLE_PUBLISH_REQUEST = 'TOGGLE_PUBLISH_REQUEST'
export const TOGGLE_PUBLISH_SUCCESS = 'TOGGLE_PUBLISH_SUCCESS'
export const TOGGLE_PUBLISH_FAILURE = 'TOGGLE_PUBLISH_FAILURE'

export const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST'
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS'
export const DELETE_PAGE_FAILURE = 'DELETE_PAGE_FAILURE'

export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST'
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS'
export const FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE'

export const UPDATE_HEADER_REQUEST = 'UPDATE_HEADER_REQUEST'
export const UPDATE_HEADER_SUCCESS = 'UPDATE_HEADER_SUCCESS'
export const UPDATE_HEADER_FAILURE = 'UPDATE_HEADER_FAILURE'

export const CREATE_MEDIA_REQUEST = 'CREATE_MEDIA_REQUEST'
export const CREATE_MEDIA_SUCCESS = 'CREATE_MEDIA_SUCCESS'
export const CREATE_MEDIA_FAILURE = 'CREATE_MEDIA_FAILURE'

export const UPDATE_MEDIA_REQUEST = 'UPDATE_MEDIA_REQUEST'
export const UPDATE_MEDIA_SUCCESS = 'UPDATE_MEDIA_SUCCESS'
export const UPDATE_MEDIA_FAILURE = 'UPDATE_MEDIA_FAILURE'

export const DELETE_MEDIA_REQUEST = 'DELETE_MEDIA_REQUEST'
export const DELETE_MEDIA_SUCCESS = 'DELETE_MEDIA_SUCCESS'
export const DELETE_MEDIA_FAILURE = 'DELETE_MEDIA_FAILURE'

export const UPLOAD_FILE_MEDIA_REQUEST = 'UPLOAD_FILE_MEDIA_REQUEST'
export const UPLOAD_FILE_MEDIA_SUCCESS = 'UPLOAD_FILE_MEDIA_SUCCESS'
export const UPLOAD_FILE_MEDIA_FAILURE = 'UPLOAD_FILE_MEDIA_FAILURE'

export const UPDATE_FILE_MEDIA_REQUEST = 'UPDATE_FILE_MEDIA_REQUEST'
export const UPDATE_FILE_MEDIA_SUCCESS = 'UPDATE_FILE_MEDIA_SUCCESS'
export const UPDATE_FILE_MEDIA_FAILURE = 'UPDATE_FILE_MEDIA_FAILURE'

export const DELETE_FILE_MEDIA_REQUEST = 'DELETE_FILE_MEDIA_REQUEST'
export const DELETE_FILE_MEDIA_SUCCESS = 'DELETE_FILE_MEDIA_SUCCESS'
export const DELETE_FILE_MEDIA_FAILURE = 'DELETE_FILE_MEDIA_FAILURE'

export const SORT_GALLERY_MEDIA_REQUEST = 'SORT_GALLERY_MEDIA_REQUEST'
export const SORT_GALLERY_MEDIA_SUCCESS = 'SORT_GALLERY_MEDIA_SUCCESS'
export const SORT_GALLERY_MEDIA_FAILURE = 'SORT_GALLERY_MEDIA_FAILURE'
