export const REQUEST_PAGES = 'REQUEST_POSTS'
export const RECEIVE_PAGES = 'RECEIVE_POSTS'
export const SET_PUBLISH_STATUS_FILTER = 'SET_PUBLISH_STATUS_FILTER'
export const SET_TEXT_SEARCH_FILTER = 'SET_TEXT_SEARCH_FILTER'
