export const REQUEST_PAGES = 'REQUEST_PAGES'
export const RECEIVE_PAGES = 'RECEIVE_PAGES'

export const SET_PUBLISH_STATUS_FILTER = 'SET_PUBLISH_STATUS_FILTER'
export const SET_TEXT_SEARCH_FILTER = 'SET_TEXT_SEARCH_FILTER'

export const CREATE_PAGE_REQUEST = 'CREATE_PAGE_REQUEST'
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS'
export const CREATE_PAGE_FAILURE = 'CREATE_PAGE_FAILURE'

export const TOGGLE_PUBLISH_REQUEST = 'TOGGLE_PUBLISH_REQUEST'
export const TOGGLE_PUBLISH_SUCCESS = 'TOGGLE_PUBLISH_SUCCESS'
export const TOGGLE_PUBLISH_FAILURE = 'TOGGLE_PUBLISH_FAILURE'

export const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST'
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS'
export const DELETE_PAGE_FAILURE = 'DELETE_PAGE_FAILURE'

export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST'
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS'
export const FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE'
